/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedFeedbackSessionIdRouteImport } from './routes/_authenticated/feedback.$sessionId'
import { Route as AuthenticatedReportSessionIdRouteImport } from './routes/_authenticated/report.$sessionId'
import { Route as AuthenticatedSessionSessionIdRouteImport } from './routes/_authenticated/session.$sessionId'
import { Route as ApiPublicHooksNoShowSweepRouteImport } from './routes/api/public/hooks/no-show-sweep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackSessionIdRoute =
  AuthenticatedFeedbackSessionIdRouteImport.update({
    id: '/feedback/$sessionId',
    path: '/feedback/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportSessionIdRoute =
  AuthenticatedReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionSessionIdRoute =
  AuthenticatedSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksNoShowSweepRoute =
  ApiPublicHooksNoShowSweepRouteImport.update({
    id: '/api/public/hooks/no-show-sweep',
    path: '/api/public/hooks/no-show-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/feedback/$sessionId': typeof AuthenticatedFeedbackSessionIdRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/hooks/no-show-sweep': typeof ApiPublicHooksNoShowSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/feedback/$sessionId': typeof AuthenticatedFeedbackSessionIdRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/hooks/no-show-sweep': typeof ApiPublicHooksNoShowSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/feedback/$sessionId': typeof AuthenticatedFeedbackSessionIdRoute
  '/_authenticated/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/_authenticated/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/hooks/no-show-sweep': typeof ApiPublicHooksNoShowSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/queue'
    | '/feedback/$sessionId'
    | '/report/$sessionId'
    | '/session/$sessionId'
    | '/api/public/hooks/no-show-sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/queue'
    | '/feedback/$sessionId'
    | '/report/$sessionId'
    | '/session/$sessionId'
    | '/api/public/hooks/no-show-sweep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_authenticated/queue'
    | '/_authenticated/feedback/$sessionId'
    | '/_authenticated/report/$sessionId'
    | '/_authenticated/session/$sessionId'
    | '/api/public/hooks/no-show-sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksNoShowSweepRoute: typeof ApiPublicHooksNoShowSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/$sessionId': {
      id: '/_authenticated/feedback/$sessionId'
      path: '/feedback/$sessionId'
      fullPath: '/feedback/$sessionId'
      preLoaderRoute: typeof AuthenticatedFeedbackSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$sessionId': {
      id: '/_authenticated/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof AuthenticatedReportSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session/$sessionId': {
      id: '/_authenticated/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/no-show-sweep': {
      id: '/api/public/hooks/no-show-sweep'
      path: '/api/public/hooks/no-show-sweep'
      fullPath: '/api/public/hooks/no-show-sweep'
      preLoaderRoute: typeof ApiPublicHooksNoShowSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedFeedbackSessionIdRoute: typeof AuthenticatedFeedbackSessionIdRoute
  AuthenticatedReportSessionIdRoute: typeof AuthenticatedReportSessionIdRoute
  AuthenticatedSessionSessionIdRoute: typeof AuthenticatedSessionSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedFeedbackSessionIdRoute: AuthenticatedFeedbackSessionIdRoute,
  AuthenticatedReportSessionIdRoute: AuthenticatedReportSessionIdRoute,
  AuthenticatedSessionSessionIdRoute: AuthenticatedSessionSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksNoShowSweepRoute: ApiPublicHooksNoShowSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
